### ISSUE TITLE
Resulting model mAP (0.556) lower than expected (0.63)

### ISSUE THREAD

**Issue by ridiculousJoe** [Tshzzz/pytorch_yolov1#11]
Hi @Tshzzz thank you for sharing this YOLOv1 implementation.
I have trained the YOLOv1 model with fc layers following your repo (trained on VOC2007 (train, valid) and tested on VOC2007 (test)), but I got an mAP of 0.556 < 0.63.
Could you please tell me what I should do to get an mAP of 0.63 as you did? Thank you very much!
My settings in config.py:
```
bbox_num = 2
box_scale = 7
lr = 1e-4

model_save_iter = 1  # epochs
epochs_start = 0
epochs_end = 150
batch_size = 20
cls_num = len(classes)

use_conv = False

## data augmentation

jitter = 0.2
hue = 0.1
saturation = 1.5
exposure = 1.5

#loss
l_coord = 5
l_noobj = 0.5

YOLO = {
    'ceils_size':7,
    'class_num':len(classes),
    'box_num':2,
    'image_size':[448,448]
}
```
My settings in main.py:
```
optimizer = optim.SGD(net.parameters(), lr=start_lr, momentum=0.9, weight_decay=5e-4)
scheduler = MultiStepLR(optimizer, milestones=[70, 130], gamma=0.1)
```

**Comment by Tshzzz** [comment]
Hello , I just update the code. Training YOLO with conv layer reach 0.64 mAp.

**Comment by ridiculousJoe** [comment]
Thank you so much for your quick update!! I will try training with FC layer now and see if it can reach that high mAP. Thanks!

**Comment by Tshzzz** [comment]
I'm not test fc layer now. If you get result, you can share with me. I think the parameters of training maybe important ,I hope you can get good result.



---Original---
