### ISSUE TITLE
Gradient overflow 

### ISSUE THREAD

**Issue by sungwool** [Tshzzz/pytorch_yolov1#13]
Thank you for sharing your code.
when I try to run your code, there are always 'Gradient overflow' problem at every iteration.
How can I solve this problem?

**Comment by ghost** [comment]
> Thank you for sharing your code.
> when I try to run your code, there are always 'Gradient overflow' problem at every iteration.
> How can I solve this problem?

hi i met this problem too. Have you solved it?
i tried decreasing batch size and apex amp opt level but still didnt work (

**Comment by sungwool** [comment]
I couldn't solve it in the end.
I think clipping the gradient can be one way.

Good luck to you.
