### ISSUE TITLE
torch.load('darknet19_448.conv.23') error

### ISSUE THREAD

**Issue by XiaodanLi001** [Tshzzz/pytorch_yolov1#5]
Could you please offer me with your pretrained model with '.pkl'? I can't load the darknet19_448.conv.23 correctly. Thank you a lot.

**Comment by Tshzzz** [comment]
See the readme step 5.You can download at this link.------------------ 原始邮件 ------------------
发件人: "XiaodanLi001"<notifications@github.com>
发送时间: 2019年8月13日(星期二) 上午9:53
收件人: "Tshzzz/pytorch_yolov1"<pytorch_yolov1@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Tshzzz/pytorch_yolov1] torch.load('darknet19_448.conv.23') error(#5)



Could you please offer me with your pretrained model with '.pkl'? I can't load the darknet19_448.conv.23 correctly. Thank you a lot.
 
&mdash;

**Comment by XiaodanLi001** [comment]
> See the readme step 5.You can download at this link.------------------ 原始邮件 ------------------ 发件人: "XiaodanLi001"<notifications@github.com> 发送时间: 2019年8月13日(星期二) 上午9:53 收件人: "Tshzzz/pytorch_yolov1"<pytorch_yolov1@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Tshzzz/pytorch_yolov1] torch.load('darknet19_448.conv.23') error(#5) Could you please offer me with your pretrained model with '.pkl'? I can't load the darknet19_448.conv.23 correctly. Thank you a lot. &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yes, I have tried it and torch.load('') gets errors. Can you load it correctly? If you can, can you offer me with your python and pytorch version? Thank you so much for your reply. I really need this pretrained model. Again, thank you.

**Comment by Tshzzz** [comment]
you can't use this pretrain weight directly. see my code network.py , line 89. I use this function to load pretrain weight.

**Comment by XiaodanLi001** [comment]
> you can't use this pretrain weight directly. see my code network.py , line 89. I use this function to load pretrain weight.

Thank you so much for your reply. I have loaded it correctly. So, this ckpt file is for extracting features only, and the output shape of feature layer is [batchsize, 1024, 14,14]. We need to train the left layers by ourselves? Errrr, so, can you share the whole ckpt like "model.pkl" in demo.py(line 68), because I want to infer it directly. Again, thank you a lot.

**Comment by Tshzzz** [comment]
Sorry, I have removed the model ckpt ... You can use maskrcnn-benckmark to do interference. https://github.com/facebookresearch/maskrcnn-benchmark

**Comment by XiaodanLi001** [comment]
> Sorry, I have removed the model ckpt ... You can use maskrcnn-benckmark to do interference. https://github.com/facebookresearch/maskrcnn-benchmark

Ok......I just want to use yolov1(pytorch) to do some project.....and you're the only one who offers the pretrained model(there's another one ,but it doesn't perform well.) Anyway, thank you a lot.

**Comment by Tshzzz** [comment]
YOLO is heavy and low. You can try SSD or other single stage detector.
