### ISSUE TITLE
图片resize

### ISSUE THREAD

**Issue by summeroyl** [Tshzzz/pytorch_yolov1#8]
你好，请问裁剪以后的图片resize到[448,448]的尺寸时，真值框不需要缩放吗？

**Comment by Tshzzz** [comment]
把框归一化到0～1之间，就不用缩放了



---原始邮件---
发件人: "summeroyl"<notifications@github.com&gt;
发送时间: 2019年11月28日(星期四) 中午11:00
收件人: "Tshzzz/pytorch_yolov1"<pytorch_yolov1@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Tshzzz/pytorch_yolov1] 图片resize (#8)



你好，请问裁剪以后的图片resize到[448,448]的尺寸时，真值框不需要缩放吗？

**Comment by summeroyl** [comment]
不好意思...还是没懂为什么?

**Comment by Tshzzz** [comment]
每个box在初始的时候都是原始值除以他对应图片尺寸之后保存的。之后改变图片尺寸不影响归一化后的box

---原始邮件---
发件人: "summeroyl"<notifications@github.com&gt;
发送时间: 2019年11月28日(星期四) 中午1:47
收件人: "Tshzzz/pytorch_yolov1"<pytorch_yolov1@noreply.github.com&gt;;
抄送: "Tshzzz"<695809401@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [Tshzzz/pytorch_yolov1] 图片resize (#8)



不好意思...还是没懂为什么?

**Comment by summeroyl** [comment]
好的，谢谢
