### ISSUE TITLE
UserWarning:indexing with dtype torch.unit8 is now deprecated

### ISSUE THREAD

**Issue by blackAndrechen** [Tshzzz/pytorch_yolov1#9]
when i run code,Keep reporting this warning error

/opt/conda/conda-bld/pytorch_1573049387353/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

**Comment by Tshzzz** [comment]
I update the code and the problem is solved
